apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-github
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-github
  template:
    metadata:
      labels:
        app: go-github
    spec:
      containers:
      - name: go-github
        image: reandreev/go-github-jwtcookie:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: go-github
spec:
  type: NodePort
  selector:
    app: go-github
  ports:
    - protocol: TCP
      port: 8080
