name: build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v4
    -
      name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.5'
    -
      name: Build
      run: go build -v ./...
