name: lint

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
