on:
  - push
  
jobs:
  minikube:
    runs-on: ubuntu-latest
    steps:
      -
        name: Start minikube
        uses: medyagh/setup-minikube@latest
      -
        name: Deploy to minikube
        run: |
          kubectl apply -f kubernetes.yaml
          kubectl wait --for=condition=ready pod -l app=go-github
      -
        name: Test service URLs
        run: |
          minikube service list
          minikube service go-github --url
          echo -n "------------------opening the service------------------"
          curl $(minikube service go-github --url)/repos
